apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    type: backend
spec:
  template:
    metadata:
      name: db-pod
      labels:
        app: db
        type: backend
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 

  replicas: 1
  selector:
    matchLabels:
      type: backend
