apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db-Service
spec:
  type: ClusterIP
  ports:
    - name: db-port
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db