apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  labels:
    app: redis-cache
    type: backend
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis-cache
        type: backend
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
          - containerPort: 6379
  replicas: 1
  selector:
    matchLabels:
      type: backend